name: crc_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - umap-learn
  - scanpy
  - anndata
  - pip
  - pip:
      - pydeseq2
      - gseapy
      - conorm