name: crc_env
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - umap-learn
  - python-igraph 
  - leidenalg
  - anndata
  - pycox
  - ipykernel
  - pip
  - pip:
      - scikit-learn
      - pydeseq2
      - gseapy
      - conorm
      - scikit-survival
      - scanpy
